export const actionTypes = {
  // AUTH ACTIONS ...

  // ACTIONS RELETED TO SINGUP AUTHENTICATION ...
  AUTH_SIGNUP_START: "AUTH_SIGNUP_START",
  AUTH_SIGNUP_SUCCESS: "AUTH_SIGNUP_SUCCESS",
  AUTH_SIGNUP_FAIL: "AUTH_SIGNUP_FAIL",

  // ACTIONS RELETED TO LOGIN AUTHENTICATION ...
  AUTH_LOGIN_START: "AUTH_LOGIN_START",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAIL: "AUTH_LOGIN_FAIL",

  // ACTIONS RELETED TO THEE LOGOUT...
  AUTH_LOGOUT: "AUTH_LOGOUT",

  // AUTH SOME THING WENT WRONG ...
  AUTH_SOMETHING_WENT_WRONG: "AUTH_SOMETHING_WENT_WRONG",
  AUTH_SOMETHING_WENT_WRONG_CLOSE: "AUTH_SOMETHING_WENT_WRONG_CLOSE",

  // PROFILE ACTIONS ...

  // PROFILE SOME THING WENT WRONG ...
  PROFILE_SOMETHING_WENT_WRONG: "PROFILE_SOMETHING_WENT_WRONG",
  PROFILE_SOMETHING_WENT_WRONG_CLOSE: "PROFILE_SOMETHING_WENT_WRONG_CLOSE",

  // ACTIONS RELETED TO GET PROFILE ...
  GET_PROFILE_START: "GET_PROFILE_START",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAIL: "GET_PROFILE_FAIL",

  // ACTIONS RELETED TO GET PROFILE BY HANDLE...
  GET_PROFILE_BY_HANDLE_START: "GET_PROFILE_BY_HANDLE_START",
  GET_PROFILE_BY_HANDLE_SUCCESS: "GET_PROFILE_BY_HANDLE_SUCCESS",
  GET_PROFILE_BY_HANDLE_FAIL: "GET_PROFILE_BY_HANDLE_FAIL",

  // ACTIONS RELETED TO  GET PROFILES ...
  GET_PROFILES_START: "GET_PROFILES_START",
  GET_PROFILES_SUCCESS: "GET_PROFILES_SUCCESS",
  GET_PROFILES_FAIL: "GET_PROFILES_FAIL",

  // ACTIONS RELETED TO CREATE PROFILE ...
  CREATE_PROFILE_START: "CREATE_PROFILE_START",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  CREATE_PROFILE_FAIL: "CREATE_PROFILE_FAIL",

  // ACTIONS RELETED TO ADD EXPERIENCE IN PROFILE ...
  ADD_EXPERIENCE_START: "ADD_EXPERIENCE_START",
  ADD_EXPERIENCE_SUCCESS: "ADD_EXPERIENCE_SUCCESS",
  ADD_EXPERIENCE_FAIL: "ADD_EXPERIENCE_FAIL",

  // ACTIONS RELETED TO ADD EDUCATION IN PROFILE ...
  ADD_EDUCATION_START: "ADD_EDUCATION_START",
  ADD_EDUCATION_SUCCESS: "ADD_EDUCATION_SUCCESS",
  ADD_EDUCATION_FAIL: "ADD_EDUCATION_FAIL",

  // ACTIONS RELETED TO DELETE ACCOUNT AND PROFILE ...
  DELETE_ACCOUNT_START: "DELETE_ACCOUNT_START",
  DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
  DELETE_ACCOUNT_FAIL: "DELETE_ACCOUNT_FAIL",

  // DELETE EXPERIENCE ...
  DELETE_EXPERIENCE_START: "DELETE_EXPERIENCE_START",
  DELETE_EXPERIENCE_SUCCESS: "DELETE_EXPERIENCE_SUCCESS",
  DELETE_EXPERIENCE_FAIL: "DELETE_EXPERIENCE_FAIL",

  // DELETE EDUCATION ...
  DELETE_EDUCATION_START: "DELETE_EDUCATION_START",
  DELETE_EDUCATION_SUCCESS: "DELETE_EDUCATION_SUCCESS",
  DELETE_EDUCATION_FAIL: "DELETE_EDUCATION_FAIL",

  // CLEAR CURRENT PROFILE...
  CLEAR_CURRENT_PROFILE: "CLEAR_CURRENT_PROFILE",

  // POST ACTIONS ...

  // AUTH SOME THING WENT WRONG ...
  POST_SOMETHING_WENT_WRONG: "POST_SOMETHING_WENT_WRONG",
  POST_SOMETHING_WENT_WRONG_CLOSE: "POST_SOMETHING_WENT_WRONG_CLOSE",

  // GET POST ...
  GET_POST_START: "GET_POST_START",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAIL: "GET_POST_FAIL",

  // GET POSTS ...
  GET_POSTS_START: "GET_POSTS_START",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAIL: "GET_POSTS_FAIL",

  // ADD POST ...
  ADD_POST_START: "ADD_POST_START",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAIL: "ADD_POST_FAIL",

  // DELETE POST ...
  DELETE_POST_START: "DELETE_POST_START",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAIL: "DELETE_POST_FAIL",

  // ADD COMMENT ...
  ADD_COMMENT_START: "ADD_COMMENT_START",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAIL: "ADD_COMMENT_FAIL",

  // DELETE COMMENT ...
  DELETE_COMMENT_START: "DELETE_COMMENT_START",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAIL: "DELETE_COMMENT_FAIL",

  // CLEAR POST AFTER LOGOUT...
  CLEAR_CURRENT_POST: "CLEAR_CURRENT_POST"
};
